# Pandas

Pandas is build on top of NumPy and provides a higher level view on data. It therefore provides Series and DataFrame (as well as Index) objects that allow attaching row and column labels to multidimensional arrays, work with missing data, and powerful data operations familiar from databases and spreadsheets.

If you use the Anaconda Python stack, pandas is already installed.

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

import pandas as pd
print("Pandas version:", pd.__version__)

NumPy version: 1.16.2
Pandas version: 0.24.2


## Series

A Series object is a one-dimensional array of indexed data.

It provides both a sequence of values (NumPy array) as well as a sequence of indices.

In [2]:
s = pd.Series([64.2, 274.3, 93.21, 52.87])
print (s)

0     64.20
1    274.30
2     93.21
3     52.87
dtype: float64


In [3]:
print(s.values)
print(type(s.values))

[ 64.2  274.3   93.21  52.87]
<class 'numpy.ndarray'>


In [4]:
print(s.index)
print(type(s.index))

RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>


In [5]:
print(s[2])
print(type(s[2]))

93.21
<class 'numpy.float64'>


In [6]:
print(s[0:2])
print(type(s[0:2]))

0     64.2
1    274.3
dtype: float64
<class 'pandas.core.series.Series'>


One way to think of a Series object is as a one-dimensionally NumPy array with an explicitely defined index. This gives further capabilities on how to use this index.

In [7]:
s = pd.Series([9.13, 5.89, 7.37, 1.93], index=['a', 'b', 'c', 'd'])
print(s)

a    9.13
b    5.89
c    7.37
d    1.93
dtype: float64


In [8]:
print(s['a']) # explicit loc
print(s['c'])

9.13
7.37


In [9]:
s['b'] = 8.98
print(s)

a    9.13
b    8.98
c    7.37
d    1.93
dtype: float64


In [10]:
print(s['a':'c'])
print('\n', s[0:2])

a    9.13
b    8.98
c    7.37
dtype: float64

 a    9.13
b    8.98
dtype: float64


**Why is the first slicing ['a':'c'] including c and the second one [0:2] not including c?** 

Slicing with the explicit index (Panda style) is inclusive, slicing with the implicit index (Python style) is exclusive. This can be confusing if the explicit index uses numbers 0, 1, 2, ..., n-1. Then the implicit index (Python style) is still used. See loc, iloc how to handle this.

In [11]:
s2 = pd.Series([9.13, 5.89, 7.37, 1.93], index=[0, 1, 2, 3])
print(s2, '\n')
print(s2[0:3]) # implicit index

0    9.13
1    5.89
2    7.37
3    1.93
dtype: float64 

0    9.13
1    5.89
2    7.37
dtype: float64


Another way to think of a Series object is as a specialization of a dictionary.

In [12]:
pop_dict = {'Berlin': 3613495, 'Munich': 1456039, 'Cologne': 1080394, 'Hamburg': 1834823, 'Frankfurt a.M.': 746878 }
pop = pd.Series(pop_dict)
print(pop)

Berlin            3613495
Munich            1456039
Cologne           1080394
Hamburg           1834823
Frankfurt a.M.     746878
dtype: int64


In [13]:
print(pop['Hamburg'])

1834823


In [14]:
print(pop['Munich':'Hamburg'])

Munich     1456039
Cologne    1080394
Hamburg    1834823
dtype: int64


## DataFrame

A DataFrame is a two-dimensional array with both flexible row indices and flexible column names. It can be though of as a sequence of aligned Series objects that share the same index.

In [15]:
area_dict = {'Berlin': 891.68, 'Munich': 310.70, 'Cologne': 405.02, 'Hamburg': 755.22, 'Frankfurt a.M.': 248.31 }
area = pd.Series(area_dict)
print(area)

Berlin            891.68
Munich            310.70
Cologne           405.02
Hamburg           755.22
Frankfurt a.M.    248.31
dtype: float64


In [16]:
cities = pd.DataFrame({'population':pop, 'area in km²':area})
cities

population  area in km²
Berlin             3613495       891.68
Munich             1456039       310.70
Cologne            1080394       405.02
Hamburg            1834823       755.22
Frankfurt a.M.      746878       248.31

In [17]:
print(cities.index)

Index(['Berlin', 'Munich', 'Cologne', 'Hamburg', 'Frankfurt a.M.'], dtype='object')


In [18]:
print(cities.columns)

Index(['population', 'area in km²'], dtype='object')


A DataFrame can also be regarded as a specialized dictionary that  maps a column name (key) to a Series (value). Columns can be accessed by the index operator using the column name. THe return type is a Series object.

In [19]:
print(cities['area in km²'])
print('\n', type(cities['area in km²']))

Berlin            891.68
Munich            310.70
Cologne           405.02
Hamburg           755.22
Frankfurt a.M.    248.31
Name: area in km², dtype: float64

 <class 'pandas.core.series.Series'>


**Careful when using the index, for a two dimensional NumPy array called arr, arr[0] gives back the first row. For a DataFrame object called df, df[col0] returns the column with the label col0 (as a Series object).**

In [20]:
a = np.random.randint(0, 10, (3,3))
print(a, '\n')
print(a[0])

[[4 1 7]
 [1 6 2]
 [2 0 9]] 

[4 1 7]


Further Serior objects can be added to an existing DataFrame using the index operator that provides a new key that denotes the column label of the Series object to be inserted.

In [21]:
vehicle_dict = {'Berlin':'B', 'Munich':'M', 'Frankfurt a.M.': 'F', 'Bremen':'HB'}
veh = pd.Series(vehicle_dict)
cities['vehicle number'] = veh
cities

population  area in km² vehicle number
Berlin             3613495       891.68              B
Munich             1456039       310.70              M
Cologne            1080394       405.02            NaN
Hamburg            1834823       755.22            NaN
Frankfurt a.M.      746878       248.31              F

### Data Indexing and Selection

If an explicit integer index is provided, that explicit index will always be used. But if such an explicit integer index is not provided, the implicit integer index can still be used.

In [22]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
print(data)

1    a
3    b
5    c
dtype: object


In [23]:
print(data[1])

a


In [24]:
print(s, '\n')
print(s[1])

a    9.13
b    8.98
c    7.37
d    1.93
dtype: float64 

8.98


Using a integer index that is not in the explicit integer index object causes an error:

In [26]:
#data(data[0])

But slicing works with the integer index, but maybe not as expected.

In [27]:
print(data, '\n')
print(data[1:3])

1    a
3    b
5    c
dtype: object 

3    b
5    c
dtype: object


In [28]:
cities

population  area in km² vehicle number
Berlin             3613495       891.68              B
Munich             1456039       310.70              M
Cologne            1080394       405.02            NaN
Hamburg            1834823       755.22            NaN
Frankfurt a.M.      746878       248.31              F

If (string) labels are provided for columns, we can also use these (string) labels like attributes of the DataFrame to access the Series object with these labels. But only if there is no naming conflict, e.g. with method names.

In [29]:
print(cities['population'])

Berlin            3613495
Munich            1456039
Cologne           1080394
Hamburg           1834823
Frankfurt a.M.     746878
Name: population, dtype: int64


In [30]:
cities_pop = cities.population
print(cities_pop)

Berlin            3613495
Munich            1456039
Cologne           1080394
Hamburg           1834823
Frankfurt a.M.     746878
Name: population, dtype: int64


Insert a new column as the result of a computation with a universal function.

In [31]:
cities['density'] = cities['population'] / cities['area in km²']
cities

population  area in km² vehicle number      density
Berlin             3613495       891.68              B  4052.457160
Munich             1456039       310.70              M  4686.317992
Cologne            1080394       405.02            NaN  2667.507777
Hamburg            1834823       755.22            NaN  2429.521199
Frankfurt a.M.      746878       248.31              F  3007.845032

In [32]:
cities.values

array([[3613495, 891.68, 'B', 4052.45715951911],
       [1456039, 310.7, 'M', 4686.3179916317995],
       [1080394, 405.02, nan, 2667.507777393709],
       [1834823, 755.22, nan, 2429.5211991207857],
       [746878, 248.31, 'F', 3007.8450324191535]], dtype=object)

In [33]:
cities.T

Berlin   Munich  Cologne  Hamburg Frankfurt a.M.
population      3613495  1456039  1080394  1834823         746878
area in km²      891.68    310.7   405.02   755.22         248.31
vehicle number        B        M      NaN      NaN              F
density         4052.46  4686.32  2667.51  2429.52        3007.85

Accessing a specific row:

In [34]:
cities.values[1]

array([1456039, 310.7, 'M', 4686.3179916317995], dtype=object)

Accessing a specific column:

In [35]:
cities['population']

Berlin            3613495
Munich            1456039
Cologne           1080394
Hamburg           1834823
Frankfurt a.M.     746878
Name: population, dtype: int64

### loc and iloc indexers for Series objects

The **loc** attribute allows indexing and slicing that always references the explicit index.

In [36]:
print(data)

1    a
3    b
5    c
dtype: object


In [37]:
print(data.loc[1])

a


In [38]:
data.loc[1:3]

1    a
3    b
dtype: object

The **iloc** attribute allows indexing and slicing that always references the implicit Python-style index.

In [39]:
data.iloc[1]

'b'

In [40]:
data.iloc[1:3]

3    b
5    c
dtype: object

**The explicit indexers loc and iloc make cleaner code and are suggested to be used, especially with explicit integer indexes!**

### loc and iloc for DataFrame objects

In [41]:
cities

population  area in km² vehicle number      density
Berlin             3613495       891.68              B  4052.457160
Munich             1456039       310.70              M  4686.317992
Cologne            1080394       405.02            NaN  2667.507777
Hamburg            1834823       755.22            NaN  2429.521199
Frankfurt a.M.      746878       248.31              F  3007.845032

The iloc indexer allows to index the underlying array as if it is a simple NumPy array.

In [42]:
cities.iloc[1:4, :2]

population  area in km²
Munich      1456039       310.70
Cologne     1080394       405.02
Hamburg     1834823       755.22

Using the explicit index of the DataFrame with loc.

In [43]:
cities.loc[:'Cologne', 'vehicle number':'density']

vehicle number      density
Berlin               B  4052.457160
Munich               M  4686.317992
Cologne            NaN  2667.507777

### What else is there?

Combine masking and fancy indexing:

In [44]:
cities.loc[cities.density > 3000, ['population', 'density']]

population      density
Berlin             3613495  4052.457160
Munich             1456039  4686.317992
Frankfurt a.M.      746878  3007.845032

In [45]:
cities.density > 3000

Berlin             True
Munich             True
Cologne           False
Hamburg           False
Frankfurt a.M.     True
Name: density, dtype: bool

In [46]:
cities.loc[[True, True, False, False, True], ['population', 'density']]

population      density
Berlin             3613495  4052.457160
Munich             1456039  4686.317992
Frankfurt a.M.      746878  3007.845032